config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :drivers
  resources :vehicles
  resources :vehicle_types

  root :to => "vehicles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/driver.rb
class Driver < ApplicationRecord
    has_many :trips

    validates :first_name, :last_name, :document, :picture_url, :presence => true

    def full_name
        self.first_name + " " + self.last_name
    end

    def kilometers
        km_recorridos = 0
        self.trips.each do |viaje|
            km_recorridos += viaje.kilometers
        end
        km_recorridos
    end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:first_name, :last_name, :document, :picture_url)
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :document %>
    <%= form.number_field :document %>
  </div>

  <div class="field">
    <%= form.label :picture_url %>
    <%= form.text_field :picture_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>
<div class="card-columns">
  <% @drivers.each do |driver| %>
    <div class="card" style="width: 18rem;">
      <div style="width:100%; height: 200px; background-image: url(<%= driver.picture_url %>); background-size:cover; background-position:center;"></div>
      <div class="card-body">
        <h5 class="card-title"><%= driver.full_name %></h5>
        <p class="card-text">Conductor.</p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><b>DNI:</b> <%= driver.document %></li>
        <li class="list-group-item"><b>KM Recorridos:</b> <%= driver.kilometers %></li>
        <li class="list-group-item"><%= link_to 'Ver Viajes', trips_path(:chofer_id => driver.id), :class=>"card-link" %></li>
      </ul>
      <div class="card-body">
        <%= link_to 'Ver Detalle', driver, :class=>"card-link" %>
        <%= link_to 'Edit', edit_driver_path(driver),:class=>"card-link" %>
        <%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' },:class=>"card-link" %>
      </div>
    </div>
  <% end %>
</div>
<br>

<%= link_to 'New Driver', new_driver_path, :class=>"btn btn-primary active" %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @driver.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @driver.last_name %>
</p>

<p>
  <strong>Document:</strong>
  <%= @driver.document %>
</p>

<p>
  <strong>Picture url:</strong>
  <%= @driver.picture_url %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>