config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :drivers
  resources :vehicles
  resources :vehicle_types

  root :to => "vehicles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :vehicle_type
  has_many :trips
  validates :brand, :model, :plate, :year, :vehicle_type_id, :presence => true

  validate :according_to_type

  def according_to_type
    @type = VehicleType.find(vehicle_type_id);
    errors.add(:max_weight, 'cant be nil')  if (@type.name == "Carga" && max_weight.nil?)
    errors.add(:passenger_capacity, 'cant be nil')  if (@type.name == "Transporte" && passenger_capacity.nil?)
  end

  def describe
    self.brand + " " + self.model + " " + self.year.to_s + " (" + self.plate + ")"
  end

  def kilometers
    km_recorridos = 0
    self.trips.each do |viaje|
        km_recorridos += viaje.kilometers
    end
    km_recorridos
  end
end

app/models/vehicle_type.rb
class VehicleType < ApplicationRecord
    has_many :vehicles

    validates :name, :presence => true
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
    @tipos = VehicleType.all
    
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:brand, :model, :plate, :year, :vehicle_type_id, :passenger_capacity, :max_weight)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :plate %>
    <%= form.text_field :plate %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :vehicle_type_id %>
    <%= collection_select(:vehicle, :vehicle_type_id, VehicleType.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :passenger_capacity %>
    <%= form.number_field :passenger_capacity %>
  </div>

  <div class="field">
    <%= form.label :max_weight %>
    <%= form.number_field :max_weight %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>


<div class="container">
  <div class="row">
    <% @tipos.each do |tipo| %>
      <div class="col-md">
        <h5><%= tipo.name %></h5>
        <table class="table table-hover">
            <thead class="thead-dark">
              <tr>
                <th>Auto</th>
                <th>Año</th>
                <th>Kilometros</th>
                <th colspan="4"></th>
              </tr>
          </thead>
          <tbody>
              <% tipo.vehicles.each do |vehicle| %>
                <tr>
                  <td scope="row"><%= vehicle.describe %></td>
                  <td><%= vehicle.year %></td>
                  <td><%= vehicle.kilometers %></td>
                  <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-<%= vehicle.id %>">
                      Ver Viajes
                    </button></td>
                  <td><%= link_to 'Show', vehicle %></td>
                  <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
                  <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    <% end %>
  </div>
</div>


<% @tipos.each do |tipo| %>
  <% tipo.vehicles.each do |vehicle| %>
    <div class="modal fade" id="modal-<%= vehicle.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-body">
                <table class="table">
                    <thead class="thead-dark">
                      <tr>
                          <th>Date</th>
                          <th>Vehicle</th>
                          <th>Driver</th>
                          <th>Destination</th>
                          <th>Kilometers</th>
                      </tr>
                    </thead>
                  
                    <tbody>
                      <% vehicle.trips.each do |trip| %>
                        <tr>
                            <td><%= trip.date %></td>
                            <td><%= trip.vehicle.describe %></td>
                            <td><%= trip.driver.full_name %></td>
                            <td><%= trip.destination %></td>
                            <td><%= trip.kilometers %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>                              
            </div>
          </div>
        </div>
      </div>
  <% end %>
    <% end %>
<br>

<%= link_to 'New Vehicle', new_vehicle_path, :class=>"btn btn-primary active" %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @vehicle.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Plate:</strong>
  <%= @vehicle.plate %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Vehicle type:</strong>
  <%= @vehicle.vehicle_type %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>